<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Trails of Dream</title>
    <link rel="stylesheet" href ="./assets/front/css/style.css">
</head>
<body>
   
    <header>
        <h2>Je suis le header</h2>
  
    
    <nav>
   <div class="treecon">
    <a href="#"><img src="assets/front/img/LogoTofD.png" alt="logo de Trails of Dream" width="50" height="50"></a>
   
   </div>

   <div class="treenav">


    <ul>
     <li>
      <a href="?page=home">Accueil</a>

      <li>
       <a href="?page=hikingList">Liste des randonnées</a>
      </li>
      
      <li>
       <a href="?page=articles">Articles</a>
      </li>
      <li>
       <a href="?page=contact">Contactez-nous</a>
      </li>
    </ul>
    
     <h1>Trails of Dream</h1>
    </header>
