<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Trails of Dream</title>
    <link rel="stylesheet" href ="./assets/front/css/style.css">
</head>
<body>
   
    <header>
        <h2>Je suis le header</h2>
  
    
    <nav>
  
    <a href="/TrailsOfDream/public/home"> <img src="<?=$base_uri[0];?>/public/assets/front/img/LogoTofD.png" alt="logo de Trails of Dream" width="50" height="50"></a>


    <ul>
     <li>
      <a href="/TrailsOfDream/public/home">Accueil</a>

      <li>
       <a href="/TrailsOfDream/public/add">Ajouter une randonnée</a>
      </li>
      
      <li>
       <a href="/TrailsOfDream/public/update">Modifier une randonnée</a>
      </li>
      <li>
       <a href="/TrailsOfDream/public/contact">Contactez-nous</a>
      </li>
       <li>
       <a href="/TrailsOfDream/public/404">Erreur</a>
      </li>
      <li>
       <a href="/TrailsOfDream/public/login">Connexion</a>
      </li>
      <li>
       <a href="/TrailsOfDream/public/register">Inscription</a>
      </li>
      
      <!--<li>
       <a href="/TrailsOfDream/public/admin" target="_blank">Admin</a>
      </li>-->
    </ul>
    
     <h1>Trails of Dream</h1>
    </header>
