<main class="formContainer">
    <h1>Ajouter une randonnée</h1>
    <?php
     if (isset($data)) {
        foreach ($data as $key => $message) {
        echo $message;
       }
     }
    ?>
     
    <form class="user" action="" method="post">
        <input type="hidden" name="hikingid" value=""/>
        <input type="text" name="image" placeholder="Nom de l'image (ex: nom.jpg)" class="" value="">
        <input type="text" name="title" class="" placeholder="Titre de l'article" value="">
        <textarea name="description" id="" rows="10" class="" placeholder="Contenu de l'article "></textarea>
        <input type="text" name="level" placeholder="Niveau"/>
        <input type="number" name="ascent" placeholder="Dénivelé positif"/>
        <input type="number" name="descent" placeholder="Dénivelé négatif"/>
        <input type="number" name="duration" placeholder="Durée"/>
        <input type="number" name="length" placeholder="Longueur"/>
        <input type="text" name="position" placeholder="Position"/>
        <!-- bouton submit pour identifier le formulaire dans le AdminController  -->
        <input type="submit" class="" name="addHikingForm" value="Créer l'article">
    </form>
</main>