<h1>Messages</h1>
<main class="tableContainer">
    <div class="card">
        <div class="msgTable">
            <?php ($data['messages']); ?>
            <?php
            if (isset($data['infos'])) {    
             echo $data['infos'];
            }
            ?>
            <table class="customTable">
                <thead>
                    <tr>
                      <th>Nom</th>
                      <th>Mail</th>
                      <th>Messages</th>
                      <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data['messages'] as $key => $messages) : ?>
                    <tr>
                        <td><?= $messages->getName(); ?></td>    
                        <td><a href="mailto:<?= $messages->getMail(); ?>"><?= $messages->getMail(); ?></a></td>
                        <td class="msg"><?= $messages->getMessage(); ?></td>
                        <td>
                            <form class="" action="" method="post">
                                <input type="hidden" name="contactid" value="<?= $messages->getId(); ?>">
                                <input class="" name="contactForm" type="submit" value="Supprimer">
                            </form>
                        </td>    
                    </tr>
                </tbody>
                <?php endforeach ?>
            </table>
        </div>
    </div>
</main>