<main class="tableContainer">
    <div class="card">
        <div class="msgTable">
            <?php
            if (isset($data['infos'])) {    
             echo $data['infos'];
            }
            ?>
          <table class="customTable">
            <thead>
              <tr>
                <th>Image</th>
                <th>Titre</th>
                <th>Durée</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
                 <?php foreach ($data['posts'] as $key => $post) : ?>
              <tr>
                <td><img class="" src="<?= $base_uri[0]; ?>/public/assets/front/img/<?= $post->getImage(); ?>" alt=""></td>    
                <td><?= $post->getTitle(); ?></td>
                <td><?= $post->getDuration(); ?> h</td>
                <td>
                  <form class="" action="" method="post">
                      <input type="hidden" name="hikingid" value="<?= $post->getId(); ?>">
                      <input class="" name="deleteHikingForm" type="submit" value="Supprimer">
                  </form>
                  <a class="" href="<?= $base_uri[0]; ?>/public/admin/update/<?= $post->getId(); ?>">Modifier</a>
                </td>    
              </tr>
            </tbody>
            <?php endforeach ?>
          </table>
      </div>
    </div>
</main>    