<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Trails of Dream</title>
    <link rel="stylesheet" href ="./assets/front/css/style.css">
</head>
<body>
   
    <header>
        <h2>Je suis le header de la page admin</h2>
  
    
    <nav>
   <div class="treecon">
    <a href="#"><img src="<?=$base_uri[0];?>/public/assets/front/img/LogoTofD.png" alt="logo de Trails of Dream" width="50" height="50"></a>
   
   </div>

   <div class="treenav">


    <ul>
     <li>
      <a href="/TrailsOfDream/public/home">Accueil</a>

      <li>
       <a href="/TrailsOfDream/public/add.phtml">Ajouter une randonnée</a>
      </li>
      
      <li>
       <a href="/TrailsOfDream/public/update.phtml">Modifier une randonnée</a>
      </li>
      <li>
       <a href="/TrailsOfDream/public/contact">Contactez-nous</a>
      </li>
    </ul>
    
     <h1>Trails of Dream</h1>
    </header>
