<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <title>Trails of Dream</title>
    <link rel="icon" type="image/x-icon" href="<?=$base_uri[0];?>/public/assets/LogoTofD.png">
    <link rel="stylesheet" href ="<?=$base_uri[0];?>/public/assets/style.min.css">
</head>

<body>
  <header>
      <nav class="nav">
            <div class="navContainer">
                <div class="logo">
                    <a href="/TrailsOfDream/public/home"> 
                        <img src="<?=$base_uri[0];?>/public/assets/front/img/LogoTofD.png" alt="logo de Trails of Dream" width="50" height="50">
                    </a>
                </div>
                <div class="navList" id="mainNavList">
                  <ul>
                   <li><a href="<?= $base_uri[0]; ?>/public/admin/admin">Accueil Admin</a></li>
                   <li><a href="<?= $base_uri[0]; ?>/public/admin/add/">Ajout Rando</a></li>
                   <li><a href="<?= $base_uri[0]; ?>/public/adminMessages">Messages</a></li>
                   <li><a href="<?= $base_uri[0]; ?>/public/adminUserList">Liste Utilisateurs</a></li>
                   <li><a class="" href="<?= $base_uri[0]; ?>/public/logout">Déconnexion</a></li>
                  </ul>
                </div> 
                <div class="navButton">
                    <button class="mainNavButton" id="navMediaButton">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                </div>
            </div>
       </nav>
       <div class="space"></div>
    </header>