<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Trails of Dream</title>
    <link rel="stylesheet" href ="<?=$base_uri[0];?>/public/assets/style.css">
</head>
<body>
   
    <header>
        <h1>Je suis le header de la page admin</h1>
  
    
    <nav>
   <div class="treecon">
    <a href="#"><img src="<?=$base_uri[0];?>/public/assets/front/img/LogoTofD.png" alt="logo de Trails of Dream" width="50" height="50"></a>
   
   </div>

   <div class="treenav">


    <ul>
     <li>
      <a href="/TrailsOfDream/public/home">Accueil</a>
      </li>
      
       <li>
      <a href="<?= $base_uri[0]; ?>/public/admin/">Accueil admin</a>
      </li>
      
      <li>
       <a href="<?= $base_uri[0]; ?>/public/admin/add/">Ajouter une randonnée</a>
      </li>
      
     
      <li>
       <a href="<?= $base_uri[0]; ?>/public/adminMessages">Consulter les messages</a>
      </li>
      
      
      <li>
       <a href="<?= $base_uri[0]; ?>/public/adminUserList">Consulter la liste d'utilisateurs</a>
      </li>
      
      <li> <a class="" href="<?= $base_uri[0]; ?>/public/logout">Déconnexion</a> </li>
    </ul>
    
     <h1>Trails of Dream</h1>
    </header>
