<main class="container">
    <div class="card">
        <h2>Politique de Confidentialité Trails Of Dream</h2>
        <p>Date d'entrée en vigueur : 23 Décembre 2002</p>
        <p>Trails Of Dream, notre entreprise exploite le site web [TrailsOfDream.com]. Cette page vous informe de nos politiques concernant la collecte, l'utilisation et la divulgation des Informations Personnelles que nous recevons des utilisateurs du Site.</p>
        <p>Nous utilisons vos informations personnelles uniquement pour fournir et améliorer Trails Of Dream. En utilisant Trails Of Dream, vous consentez à la collecte et à l'utilisation d'informations conformément à cette politique.</p>
        <h2>Collecte et utilisation d'informations</h2>
        <p>Pendant que vous utilisez Trails Of Dream, nous pouvons vous demander de nous fournir certaines informations personnelles identifiables pouvant être utilisées pour vous contacter ou vous identifier. Les informations personnelles identifiables peuvent inclure, votre nom, votre prénom et votre adresse mail.</p>
        <h2>Protection de vos informations</h2>
        <p>La sécurité de vos Informations Personnelles est importante pour nous, mais rappelez-vous qu'aucune méthode de transmission sur Internet ou méthode de stockage électronique n'est sécurisée à 100 %. Bien que nous nous efforcions d'utiliser des moyens commercialement acceptables pour protéger vos Informations Personnelles, nous ne pouvons pas garantir leur sécurité absolue.</p>
        <h2>Partage d'informations personnelles</h2>
        <p>Nous ne vendons, n'échangeons et ne louons pas vos informations personnelles à des tiers. Nous pouvons partager des informations agrégées et anonymes sur les visiteurs et utilisateurs avec des partenaires de confiance pour les activités susmentionnées.</p>
        <h2>Cookies</h2>
        <p>Les cookies sont des fichiers avec une petite quantité de données, qui peuvent inclure un identifiant unique anonyme. Les cookies sont envoyés à votre navigateur à partir d'un site web et sont stockés sur le disque dur de votre ordinateur.</p>
        <p>Comme de nombreux sites, nous utilisons des "cookies" pour collecter des informations. Vous pouvez indiquer à votre navigateur de refuser tous les cookies ou d'indiquer quand un cookie est envoyé. Cependant, si vous n'acceptez pas les cookies, vous ne pourrez peut-être pas utiliser certaines parties de Trails Of Dream.</p>
        <p>En utilisant Trails Of Dream, vous consentez à l'utilisation de cookies.</p>
        <h2>Liens Vers D'Autres Sites</h2>
        <p>Trails Of Dream peut contenir des liens vers d'autres sites qui ne sont pas exploités par nous. Si vous cliquez sur un lien tiers, vous serez dirigé vers le site tiers. Nous vous conseillons vivement de consulter la politique de confidentialité de chaque site que vous visitez.</p>
        <h2>Modifications de cette politique de confidentialité</h2>
        <p>Cette Politique de Confidentialité est en vigueur à partir de la date d'entrée en vigueur et restera en vigueur, sauf en ce qui concerne les modifications de ses dispositions à l'avenir, qui seront en vigueur immédiatement après leur publication sur cette page.</p>
        <p>Nous nous réservons le droit de mettre à jour ou de modifier notre Politique de Confidentialité à tout moment et vous devez consulter cette Politique de Confidentialité périodiquement. Votre utilisation continue du Service après la publication de toute modification de la Politique de Confidentialité sur cette page constituera votre reconnaissance des modifications et votre consentement à respecter et à être lié par la Politique de Confidentialité modifiée.</p>
        <h2>Nous Contacter</h2>
        <p>Si vous avez des questions concernant cette Politique de Confidentialité, veuillez nous contacter à l'adresse <a href="mailto:contact@trailsofdream.com">contact@trailsofdream.com</a>.</p>
    </div>
</main>    