<main class="formContainer">
     <?php if (isset($data)) {
         foreach ($data as $value) {
             echo $value;
         }
      } ?>

    <form class="user" action="" method="post">
        
        <h3>Contact</h3>
        
        <input type="hidden" name="contactid" value=""/>
        <input type="text" name="name" placeholder="Nom" value="<?php if (!empty($_POST['name'])){
            echo $_POST['name'];
        } ?>">
        <input type="text" name="mail" placeholder="Adresse mail" value="<?php if (!empty($_POST['mail'])){
            echo $_POST['mail'];
        } ?>">
        <textarea name="message"  placeholder="Message"><?php if (!empty($_POST['message'])){
            echo $_POST['message'];
        } ?></textarea>
        <input name="contactForm" type="submit" value="Envoyer"/>
    </form>
</main>