<h1>Je suis la page de détail de la randonnée</h1>


 <h1><?= $data->getTitle(); ?></h1>  
 
 <img src="assets/front/img/<?= $data->getImage(); ?>">
 <p><?= $data->getDescription(); ?></p>
 <p><?= $data->getLevel(); ?> </p>
 <p><?= $data->getAscent(); ?> mètres</p>
 <p><?= $data->getDuration(); ?> heures</p>
 <p><?= $data->getLength(); ?> km</p>
 <p><?= $data->getPosition(); ?></p>
 

  

                    
