<main class="formContainer">
        <?php if (isset($data)) {
            foreach ($data as $value) {
                echo $value;
            }
        } ?>
        
        <form class="user" method="post">
            <h3>Connexion</h3>
            <input type="email" name="mail" placeholder="Mail">
            <input type="password" name="password" placeholder="Mot de passe">
            <input type="submit" name="loginForm" value="Connexion">
        </form>
         <div class="logDiv">
            <a class="btnLog" href="/TrailsOfDream/public/register">Créer un compte</a>
        </div>
</main>